{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "config.json",
    "master-service.json",
    "master-headless.json",
    "master.json",
    "replica-service.json",
    "replica-headless.json",
    "replica.json"
  ]
}
