apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- config.yaml
- master-service.yaml
- master-headless.yaml
- master.yaml
- replica-service.yaml
- replica-headless.yaml
- replica.yaml
