apiVersion: v1
kind: Service
metadata:
  name: shared-redis-replica-headless
  namespace: databases
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/component: replica
    app.kubernetes.io/name: shared-redis
