apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: vote-admin
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  hosts:
  - vote-admin.rvkang.app
  exportTo:
  - .
  gateways:
  - vote-public
  http:
  - match:
    - port: 443
    route:
    - destination:
        host: vote-admin.vote.svc.cluster.local
        port:
          number: 3001
