apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: vote-ui-runtime
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: vote
  config: prd
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-vote-prd
    namespace: doppler-operator-system
  managedSecret:
    name: vote-ui-runtime
    namespace: vote
    type: Opaque
  secrets:
  - AUTH_OIDC_ISSUER
  - AUTH_OIDC_TENANT_CODE
  - AUTH_E_VOTE_RESOURCE
  - AUTH_E_VOTE_SECRET
  - AUTH_TRUST_HOST
  - VOTE_API_BASE_URL
  - VOTE_UI_AUTH_SECRET
  - VOTE_UI_AUTH_URL
  processors:
    AUTH_OIDC_ISSUER:
      type: plain
      asName: AUTH_OIDC_ISSUER
    AUTH_OIDC_TENANT_CODE:
      type: plain
      asName: AUTH_OIDC_TENANT_CODE
    AUTH_E_VOTE_RESOURCE:
      type: plain
      asName: AUTH_E_VOTE_RESOURCE
    AUTH_E_VOTE_SECRET:
      type: plain
      asName: AUTH_E_VOTE_SECRET
    AUTH_TRUST_HOST:
      type: plain
      asName: AUTH_TRUST_HOST
    VOTE_API_BASE_URL:
      type: plain
      asName: VOTE_API_BASE_URL
    VOTE_UI_AUTH_SECRET:
      type: plain
      asName: AUTH_SECRET
    VOTE_UI_AUTH_URL:
      type: plain
      asName: AUTH_URL
