{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "namespace.json",
    "postgresql-podmonitor.json",
    "redis-metrics-master.json",
    "redis-metrics-replica.json",
    "redis-podmonitor.json",
    "database-rules.json",
    "grafana-certificate.json",
    "grafana-gateway.json",
    "grafana-route.json",
    "grafana-destination.json"
  ]
}
