apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- postgresql-podmonitor.yaml
- redis-metrics-master.yaml
- redis-metrics-replica.yaml
- redis-podmonitor.yaml
- database-rules.yaml
- grafana-certificate.yaml
- grafana-gateway.yaml
- grafana-route.yaml
- grafana-destination.yaml
