apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vote-ui.yaml
- vote-ui-service.yaml
- vote-admin.yaml
- vote-admin-service.yaml
- vote-authz.yaml
- vote-authz-service.yaml
- redis-transport.yaml
- vote-server.yaml
- vote-worker.yaml
- vote-server-service.yaml
