apiVersion: v1
kind: Service
metadata:
  name: vote-admin
  namespace: vote-dev
spec:
  selector:
    app.kubernetes.io/name: vote-admin
    app.kubernetes.io/part-of: vote
  ports:
  - name: http
    port: 3001
    targetPort: http
