apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  selector:
    matchLabels: &id001
      app.kubernetes.io/name: account
      app.kubernetes.io/part-of: gaegaeting
  template:
    metadata:
      labels: *id001
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: account
        image: ghcr.io/kangjuhyup/gaegaeting/account:sha-ea4d9c5c210b543ba8e6893ca4a0b337cc0c1f4f@sha256:77f8843f7e05bb5957fe00d2fbcdcff72950f515acd871130531225f9cf5fdf1
        ports:
        - name: http
          containerPort: 2800
        envFrom:
        - secretRef:
            name: gaegaeting-account-runtime
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        startupProbe:
          httpGet:
            path: /account/health
            port: http
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /account/health
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /account/health
            port: http
          periodSeconds: 20
          failureThreshold: 3
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/database/ca.crt
        volumeMounts:
        - name: db-ca
          mountPath: /etc/database
          readOnly: true
      volumes:
      - name: db-ca
        secret:
          secretName: gaegaeting-db-ca
