apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: admin-ui
      app.kubernetes.io/part-of: gaegaeting
  template:
    metadata:
      labels:
        app.kubernetes.io/name: admin-ui
        app.kubernetes.io/part-of: gaegaeting
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: admin-ui
        image: ghcr.io/kangjuhyup/gaegaeting/admin-ui:sha-7c06eaefbfd55186e6d6503c8f95f061f3ee2b94@sha256:2940a65d00584446269f856783b4c3db56ae0649d943920f1daa88ece84b19dc
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - secretRef:
            name: gaegaeting-admin-ui-runtime
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          httpGet:
            path: /admin/health
            port: http
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /admin/health
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /admin/health
            port: http
          periodSeconds: 20
          failureThreshold: 3
  replicas: 0
