apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: admin-ui
      app.kubernetes.io/part-of: gaegaeting
  template:
    metadata:
      labels:
        app.kubernetes.io/name: admin-ui
        app.kubernetes.io/part-of: gaegaeting
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: admin-ui
        image: ghcr.io/kangjuhyup/gaegaeting/admin-ui:sha-b7fe0e0525697e6e57ae11157b4b826696f4c50c@sha256:c23dcc189626de016abbd84d66c4dfc4d3cb8f822d0e37f9ccc09ad9a9ccb7f1
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - secretRef:
            name: gaegaeting-admin-ui-runtime
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          httpGet:
            path: /admin/health
            port: http
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /admin/health
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /admin/health
            port: http
          periodSeconds: 20
          failureThreshold: 3
  replicas: 0
