apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  selector:
    matchLabels: &id001
      app.kubernetes.io/name: challenge
      app.kubernetes.io/part-of: gaegaeting
  template:
    metadata:
      labels: *id001
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: challenge
        image: ghcr.io/kangjuhyup/gaegaeting/challenge:sha-dfd6fca8b5297870fa9024622efd55b53c2a4488@sha256:3fabb671c8e72b9431d5d1716b09f818c377d4da94a8a0152b3bd38a35959bd6
        ports:
        - name: http
          containerPort: 2803
        envFrom:
        - secretRef:
            name: gaegaeting-challenge-runtime
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        startupProbe:
          httpGet:
            path: /challenge/health
            port: http
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /challenge/health
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /challenge/health
            port: http
          periodSeconds: 20
          failureThreshold: 3
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/database/ca.crt
        volumeMounts:
        - name: db-ca
          mountPath: /etc/database
          readOnly: true
      volumes:
      - name: db-ca
        secret:
          secretName: gaegaeting-db-ca
