apiVersion: v1
kind: Service
metadata:
  name: challenge
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  selector:
    app.kubernetes.io/name: challenge
    app.kubernetes.io/part-of: gaegaeting
  ports:
  - name: http
    port: 2803
    targetPort: http
