apiVersion: batch/v1
kind: Job
metadata:
  name: challenge-migration-dfd6fca8b529
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  suspend: false
  backoffLimit: 0
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: challenge
        app.kubernetes.io/part-of: gaegaeting
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: challenge
        image: ghcr.io/kangjuhyup/gaegaeting/challenge:sha-dfd6fca8b5297870fa9024622efd55b53c2a4488@sha256:3fabb671c8e72b9431d5d1716b09f818c377d4da94a8a0152b3bd38a35959bd6
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/database/ca.crt
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: gaegaeting-challenge-runtime
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: gaegaeting-challenge-runtime
              key: DATABASE_PORT
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: gaegaeting-challenge-runtime
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gaegaeting-challenge-runtime
              key: DATABASE_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: gaegaeting-challenge-runtime
              key: DATABASE_NAME
        - name: DATABASE_SSL_MODE
          valueFrom:
            secretKeyRef:
              name: gaegaeting-challenge-runtime
              key: DATABASE_SSL_MODE
        volumeMounts:
        - name: db-ca
          mountPath: /etc/database
          readOnly: true
        workingDir: /app
        command:
        - node
        - dist/src/migrations/migrate.js
      volumes:
      - name: db-ca
        secret:
          secretName: gaegaeting-db-ca
      restartPolicy: Never
