apiVersion: v1
kind: Service
metadata:
  name: edge-authz
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  selector:
    app.kubernetes.io/name: edge-authz
    app.kubernetes.io/part-of: gaegaeting
  ports:
  - name: http
    port: 4010
    targetPort: http
