apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  selector:
    matchLabels: &id001
      app.kubernetes.io/name: gateway
      app.kubernetes.io/part-of: gaegaeting
  template:
    metadata:
      labels: *id001
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: gateway
        image: ghcr.io/kangjuhyup/gaegaeting/gateway:sha-7c3733450107934f08130f0ac7d0db1a8f54c59a@sha256:545b3a431c51ef65cdd63f99eed5a25dcd60a8be39880c68f62469236c40d303
        ports:
        - name: http
          containerPort: 4000
        envFrom:
        - secretRef:
            name: gaegaeting-gateway-runtime
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        startupProbe:
          httpGet:
            path: /gateway/health
            port: http
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /gateway/health
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /gateway/health
            port: http
          periodSeconds: 20
          failureThreshold: 3
