apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  selector:
    matchLabels: &id001
      app.kubernetes.io/name: gateway
      app.kubernetes.io/part-of: gaegaeting
  template:
    metadata:
      labels: *id001
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: gateway
        image: ghcr.io/kangjuhyup/gaegaeting/gateway:sha-905cccfafe734e4a3271721b14d512e97904a162@sha256:2d8921ff94d026bb519e5edf193ae69740f57d39a09f3470d4c6d273798716d2
        ports:
        - name: http
          containerPort: 4000
        envFrom:
        - secretRef:
            name: gaegaeting-gateway-runtime
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        startupProbe:
          httpGet:
            path: /gateway/health
            port: http
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /gateway/health
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /gateway/health
            port: http
          periodSeconds: 20
          failureThreshold: 3
