apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-ui
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  selector:
    matchLabels: &id001
      app.kubernetes.io/name: integration-ui
      app.kubernetes.io/part-of: gaegaeting
  template:
    metadata:
      labels: *id001
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: integration-ui
        image: ghcr.io/kangjuhyup/gaegaeting/integration-ui:sha-2ca2b5e38403f952d31fed3695b8263352a0564d@sha256:96f81cb9500e99e4c214b54a30859ab3bbc13e2460db6dbdedaffd84645251e0
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - secretRef:
            name: gaegaeting-integration-ui-runtime
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        startupProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 20
          failureThreshold: 3
