apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-ui
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  selector:
    matchLabels: &id001
      app.kubernetes.io/name: integration-ui
      app.kubernetes.io/part-of: gaegaeting
  template:
    metadata:
      labels: *id001
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: integration-ui
        image: ghcr.io/kangjuhyup/gaegaeting/integration-ui:sha-b7fe0e0525697e6e57ae11157b4b826696f4c50c@sha256:e7c903254e7bae72292251308f212eb5b8db331e5f1c2c8492dad9ba3a4ea768
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - secretRef:
            name: gaegaeting-integration-ui-runtime
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        startupProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 20
          failureThreshold: 3
