apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- account.yaml
- account-service.yaml
- match.yaml
- match-service.yaml
- gateway.yaml
- gateway-service.yaml
- edge-authz.yaml
- edge-authz-service.yaml
- integration-ui.yaml
- integration-ui-service.yaml
- edge-proxy.yaml
- edge-proxy-service.yaml
- account-migration.yaml
- match-migration.yaml
- admin-ui.yaml
- admin-ui-service.yaml
- payment.yaml
- payment-service.yaml
- payment-migration.yaml
