apiVersion: apps/v1
kind: Deployment
metadata:
  name: match
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  selector:
    matchLabels: &id001
      app.kubernetes.io/name: match
      app.kubernetes.io/part-of: gaegaeting
  template:
    metadata:
      labels: *id001
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: match
        image: ghcr.io/kangjuhyup/gaegaeting/match:sha-7c3733450107934f08130f0ac7d0db1a8f54c59a@sha256:63a719b545d6a4ca1378f2df1f6b9a07f4f3793ff5320c1d822790c96d0e1f98
        ports:
        - name: http
          containerPort: 2801
        envFrom:
        - secretRef:
            name: gaegaeting-match-runtime
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        startupProbe:
          httpGet:
            path: /match/health
            port: http
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /match/health
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /match/health
            port: http
          periodSeconds: 20
          failureThreshold: 3
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/database/ca.crt
        volumeMounts:
        - name: db-ca
          mountPath: /etc/database
          readOnly: true
      volumes:
      - name: db-ca
        secret:
          secretName: gaegaeting-db-ca
