apiVersion: apps/v1
kind: Deployment
metadata:
  name: match
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  selector:
    matchLabels: &id001
      app.kubernetes.io/name: match
      app.kubernetes.io/part-of: gaegaeting
  template:
    metadata:
      labels: *id001
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: match
        image: ghcr.io/kangjuhyup/gaegaeting/match:sha-12f9377882ae4ff7c80c8b9616cb6ae95c3fa1c7@sha256:97166be02e46cefa85feded70eaaf9c6cd1344b010e0fd6b25bb7af2b81857e1
        ports:
        - name: http
          containerPort: 2801
        envFrom:
        - secretRef:
            name: gaegaeting-match-runtime
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        startupProbe:
          httpGet:
            path: /match/health
            port: http
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /match/health
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /match/health
            port: http
          periodSeconds: 20
          failureThreshold: 3
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/database/ca.crt
        volumeMounts:
        - name: db-ca
          mountPath: /etc/database
          readOnly: true
      volumes:
      - name: db-ca
        secret:
          secretName: gaegaeting-db-ca
