apiVersion: batch/v1
kind: Job
metadata:
  name: payment-migration-75c5a2564ff3
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  suspend: false
  backoffLimit: 0
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment
        app.kubernetes.io/part-of: gaegaeting
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: payment
        image: ghcr.io/kangjuhyup/gaegaeting/payment:sha-75c5a2564ff3d87f8585672cd86c4da7422eb5d0@sha256:1371157b93112cecb6e882a23b9528db91e567c2bc1a84db9d2b59cc57fb4d1e
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/database/ca.crt
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: gaegaeting-payment-runtime
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: gaegaeting-payment-runtime
              key: DATABASE_PORT
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: gaegaeting-payment-runtime
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gaegaeting-payment-runtime
              key: DATABASE_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: gaegaeting-payment-runtime
              key: DATABASE_NAME
        - name: DATABASE_SSL_MODE
          valueFrom:
            secretKeyRef:
              name: gaegaeting-payment-runtime
              key: DATABASE_SSL_MODE
        volumeMounts:
        - name: db-ca
          mountPath: /etc/database
          readOnly: true
        workingDir: /app
        command:
        - node
        - dist/src/migrations/migrate.js
      volumes:
      - name: db-ca
        secret:
          secretName: gaegaeting-db-ca
      restartPolicy: Never
