apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  selector:
    matchLabels: &id001
      app.kubernetes.io/name: payment
      app.kubernetes.io/part-of: gaegaeting
  template:
    metadata:
      labels: *id001
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: payment
        image: ghcr.io/kangjuhyup/gaegaeting/payment:sha-75c5a2564ff3d87f8585672cd86c4da7422eb5d0@sha256:1371157b93112cecb6e882a23b9528db91e567c2bc1a84db9d2b59cc57fb4d1e
        ports:
        - name: http
          containerPort: 2802
        envFrom:
        - secretRef:
            name: gaegaeting-payment-runtime
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        startupProbe:
          httpGet:
            path: /payment/health
            port: http
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /payment/health
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /payment/health
            port: http
          periodSeconds: 20
          failureThreshold: 3
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/database/ca.crt
        volumeMounts:
        - name: db-ca
          mountPath: /etc/database
          readOnly: true
      volumes:
      - name: db-ca
        secret:
          secretName: gaegaeting-db-ca
