apiVersion: v1
data:
  nginx.conf: |
    worker_processes 1;
    pid /tmp/nginx.pid;
    error_log /dev/stderr warn;
    events { worker_connections 256; }
    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      access_log off;
      client_body_temp_path /tmp/client;
      proxy_temp_path /tmp/proxy;
      fastcgi_temp_path /tmp/fastcgi;
      uwsgi_temp_path /tmp/uwsgi;
      scgi_temp_path /tmp/scgi;
      server {
        listen 8080;
        root /usr/share/nginx/html;
        location = /healthz { return 200 "ok\n"; }
        location / { try_files $uri $uri/ /index.html; }
      }
    }
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  name: auth-ui-nginx
  namespace: auth
