apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  namespace: gaegaeting-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: chat
        resources:
          requests:
            cpu: 25m
            memory: 128Mi
          limits:
            memory: 512Mi
    metadata:
      annotations:
        infra.oci-a1.example/doppler-config: stg
