apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-authz
  namespace: gaegaeting-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: edge-authz
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            memory: 256Mi
