apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/gaegaeting
patchesStrategicMerge:
- account-patch.yaml
- match-patch.yaml
- gateway-patch.yaml
- edge-authz-patch.yaml
- integration-ui-patch.yaml
- edge-proxy-patch.yaml
- admin-ui-patch.yaml
- payment-patch.yaml
