apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: gaegaeting-dev-account-db-identity
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: gaegaeting
  config: stg
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-gaegaeting-stg
    namespace: doppler-operator-system
  managedSecret:
    name: gaegaeting-account-db-identity
    namespace: databases
    type: Opaque
  secrets:
  - ACCOUNT_DATABASE_NAME
  - ACCOUNT_DATABASE_USERNAME
  processors:
    ACCOUNT_DATABASE_NAME:
      type: plain
      asName: database
    ACCOUNT_DATABASE_USERNAME:
      type: plain
      asName: username
