apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: gaegaeting-dev-admin-ui-runtime
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: gaegaeting
  config: stg
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-gaegaeting-stg
    namespace: doppler-operator-system
  managedSecret:
    name: gaegaeting-admin-ui-runtime
    namespace: gaegaeting-dev
    type: Opaque
  secrets:
  - ADMIN_UI_APP
  - UI_OIDC_ISSUER
  - ADMIN_UI_OIDC_CLIENT_ID
  - UI_API_AUDIENCE
  - UI_ACCOUNT_GRAPHQL_URL
  - UI_GATEWAY_GRAPHQL_URL
  - UI_IMAGE_STORAGE_ORIGIN
  processors:
    UI_OIDC_ISSUER:
      type: plain
      asName: UI_OIDC_ISSUER
    UI_API_AUDIENCE:
      type: plain
      asName: UI_API_AUDIENCE
    UI_ACCOUNT_GRAPHQL_URL:
      type: plain
      asName: UI_ACCOUNT_GRAPHQL_URL
    UI_GATEWAY_GRAPHQL_URL:
      type: plain
      asName: UI_GATEWAY_GRAPHQL_URL
    UI_IMAGE_STORAGE_ORIGIN:
      type: plain
      asName: UI_IMAGE_STORAGE_ORIGIN
    ADMIN_UI_APP:
      type: plain
      asName: UI_APP
    ADMIN_UI_OIDC_CLIENT_ID:
      type: plain
      asName: UI_OIDC_CLIENT_ID
