apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: gaegaeting-dev-chat-runtime
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: gaegaeting
  config: stg
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-gaegaeting-stg
    namespace: doppler-operator-system
  managedSecret:
    name: gaegaeting-chat-runtime
    namespace: gaegaeting-dev
    type: Opaque
  secrets:
  - NODE_ENV
  - INTERNAL_AUTH_ASSERTION_SECRET
  - DATABASE_HOST
  - DATABASE_PORT
  - DATABASE_SSL_MODE
  - CHAT_DATABASE_NAME
  - CHAT_DATABASE_USERNAME
  - CHAT_DATABASE_PASSWORD
  - CHAT_SERVICE_API_PORT
  - MATCH_SERVICE_HOST
  - CHAT_KAFKA_ENABLED
  - CHAT_KAFKA_GROUP_ID
  - KAFKA_BROKERS
  - KAFKA_TOPIC_PREFIX
  processors:
    NODE_ENV:
      type: plain
      asName: NODE_ENV
    INTERNAL_AUTH_ASSERTION_SECRET:
      type: plain
      asName: INTERNAL_AUTH_ASSERTION_SECRET
    DATABASE_HOST:
      type: plain
      asName: DATABASE_HOST
    DATABASE_PORT:
      type: plain
      asName: DATABASE_PORT
    DATABASE_SSL_MODE:
      type: plain
      asName: DATABASE_SSL_MODE
    CHAT_DATABASE_NAME:
      type: plain
      asName: DATABASE_NAME
    CHAT_DATABASE_USERNAME:
      type: plain
      asName: DATABASE_USERNAME
    CHAT_DATABASE_PASSWORD:
      type: plain
      asName: DATABASE_PASSWORD
    CHAT_SERVICE_API_PORT:
      type: plain
      asName: CHAT_SERVICE_API_PORT
    MATCH_SERVICE_HOST:
      type: plain
      asName: MATCH_SERVICE_HOST
    CHAT_KAFKA_ENABLED:
      type: plain
      asName: CHAT_KAFKA_ENABLED
    CHAT_KAFKA_GROUP_ID:
      type: plain
      asName: CHAT_KAFKA_GROUP_ID
    KAFKA_BROKERS:
      type: plain
      asName: KAFKA_BROKERS
    KAFKA_TOPIC_PREFIX:
      type: plain
      asName: KAFKA_TOPIC_PREFIX
