apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: gaegaeting-dev-cloudflare
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: infrastructure
  config: prd
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-infrastructure-prd
    namespace: doppler-operator-system
  managedSecret:
    name: gaegaeting-dev-cloudflare-dns
    namespace: istio-system
    type: Opaque
  secrets:
  - CLOUDFLARE_GAEGAETING_DNS_API_TOKEN
  processors:
    CLOUDFLARE_GAEGAETING_DNS_API_TOKEN:
      type: plain
      asName: api-token
