apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: gaegaeting-dev-db-provision-runtime
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: gaegaeting
  config: dev
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-gaegaeting-dev
    namespace: doppler-operator-system
  managedSecret:
    name: gaegaeting-db-provision-runtime
    namespace: databases
    type: Opaque
  secrets:
  - DATABASE_HOST
  - DATABASE_PORT
  - ACCOUNT_DATABASE_NAME
  - ACCOUNT_DATABASE_USERNAME
  - ACCOUNT_DATABASE_PASSWORD
  - MATCH_DATABASE_NAME
  - MATCH_DATABASE_USERNAME
  - MATCH_DATABASE_PASSWORD
  processors:
    DATABASE_HOST:
      type: plain
      asName: DATABASE_HOST
    DATABASE_PORT:
      type: plain
      asName: DATABASE_PORT
    ACCOUNT_DATABASE_NAME:
      type: plain
      asName: ACCOUNT_DATABASE_NAME
    ACCOUNT_DATABASE_USERNAME:
      type: plain
      asName: ACCOUNT_DATABASE_USERNAME
    ACCOUNT_DATABASE_PASSWORD:
      type: plain
      asName: ACCOUNT_DATABASE_PASSWORD
    MATCH_DATABASE_NAME:
      type: plain
      asName: MATCH_DATABASE_NAME
    MATCH_DATABASE_USERNAME:
      type: plain
      asName: MATCH_DATABASE_USERNAME
    MATCH_DATABASE_PASSWORD:
      type: plain
      asName: MATCH_DATABASE_PASSWORD
