apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: gaegaeting-dev-edge-authz-runtime
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: gaegaeting
  config: dev
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-gaegaeting-dev
    namespace: doppler-operator-system
  managedSecret:
    name: gaegaeting-edge-authz-runtime
    namespace: gaegaeting-dev
    type: Opaque
  secrets:
  - NODE_ENV
  - EDGE_AUTHZ_HOST
  - EDGE_AUTHZ_PORT
  - EDGE_AUTH_ASSERTION_SECRET
  - OIDC_ISSUER
  - OIDC_API_AUDIENCE
  - OIDC_INTROSPECTION_CLIENT_ID
  - OIDC_INTROSPECTION_CLIENT_SECRET
  processors:
    NODE_ENV:
      type: plain
      asName: NODE_ENV
    EDGE_AUTHZ_HOST:
      type: plain
      asName: EDGE_AUTHZ_HOST
    EDGE_AUTHZ_PORT:
      type: plain
      asName: EDGE_AUTHZ_PORT
    EDGE_AUTH_ASSERTION_SECRET:
      type: plain
      asName: EDGE_AUTH_ASSERTION_SECRET
    OIDC_ISSUER:
      type: plain
      asName: OIDC_ISSUER
    OIDC_API_AUDIENCE:
      type: plain
      asName: OIDC_API_AUDIENCE
    OIDC_INTROSPECTION_CLIENT_ID:
      type: plain
      asName: OIDC_INTROSPECTION_CLIENT_ID
    OIDC_INTROSPECTION_CLIENT_SECRET:
      type: plain
      asName: OIDC_INTROSPECTION_CLIENT_SECRET
