apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gaegaeting-dev-secret-writer
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '-30'
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - gaegaeting-account-runtime
  - gaegaeting-match-runtime
  - gaegaeting-gateway-runtime
  - gaegaeting-edge-authz-runtime
  - gaegaeting-integration-ui-runtime
  - gaegaeting-proxy-runtime
  - gaegaeting-db-ca
  - gaegaeting-admin-ui-runtime
  - gaegaeting-payment-runtime
  verbs:
  - update
