apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: gaegaeting-dev-gateway-runtime
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: gaegaeting
  config: dev
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-gaegaeting-dev
    namespace: doppler-operator-system
  managedSecret:
    name: gaegaeting-gateway-runtime
    namespace: gaegaeting-dev
    type: Opaque
  secrets:
  - NODE_ENV
  - INTERNAL_AUTH_ASSERTION_SECRET
  - GATEWAY_PORT
  - GATEWAY_AUTH_MODE
  - EDGE_AUTH_ASSERTION_SECRET
  - ACCOUNT_SERVICE_URL
  - MATCH_SERVICE_URL
  - ACCOUNT_SUBJECT_RESOLUTION_URL
  - OIDC_API_AUDIENCE
  processors:
    NODE_ENV:
      type: plain
      asName: NODE_ENV
    INTERNAL_AUTH_ASSERTION_SECRET:
      type: plain
      asName: INTERNAL_AUTH_ASSERTION_SECRET
    GATEWAY_PORT:
      type: plain
      asName: GATEWAY_PORT
    GATEWAY_AUTH_MODE:
      type: plain
      asName: GATEWAY_AUTH_MODE
    EDGE_AUTH_ASSERTION_SECRET:
      type: plain
      asName: EDGE_AUTH_ASSERTION_SECRET
    ACCOUNT_SERVICE_URL:
      type: plain
      asName: ACCOUNT_SERVICE_URL
    MATCH_SERVICE_URL:
      type: plain
      asName: MATCH_SERVICE_URL
    ACCOUNT_SUBJECT_RESOLUTION_URL:
      type: plain
      asName: ACCOUNT_SUBJECT_RESOLUTION_URL
    OIDC_API_AUDIENCE:
      type: plain
      asName: OIDC_API_AUDIENCE
