apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gaegaeting-dev-secret-writer
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: '-30'
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - gaegaeting-dev-cloudflare-dns
  verbs:
  - update
