apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: gaegaeting-dev-kafka-runtime
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: gaegaeting
  config: dev
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-gaegaeting-dev
    namespace: doppler-operator-system
  managedSecret:
    name: gaegaeting-kafka-runtime
    namespace: gaegaeting-dev-kafka
    type: Opaque
  secrets:
  - KAFKA_NODE_ID
  - KAFKA_PROCESS_ROLES
  - KAFKA_LISTENERS
  - KAFKA_ADVERTISED_LISTENERS
  - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
  - KAFKA_CONTROLLER_LISTENER_NAMES
  - KAFKA_INTER_BROKER_LISTENER_NAME
  - KAFKA_CONTROLLER_QUORUM_VOTERS
  - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
  - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
  - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
  - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
  - KAFKA_NUM_PARTITIONS
  - KAFKA_AUTO_CREATE_TOPICS_ENABLE
  - KAFKA_LOG_RETENTION_HOURS
  - KAFKA_LOG_DIRS
  - KAFKA_HEAP_OPTS
  - CLUSTER_ID
  processors:
    KAFKA_NODE_ID:
      type: plain
      asName: KAFKA_NODE_ID
    KAFKA_PROCESS_ROLES:
      type: plain
      asName: KAFKA_PROCESS_ROLES
    KAFKA_LISTENERS:
      type: plain
      asName: KAFKA_LISTENERS
    KAFKA_ADVERTISED_LISTENERS:
      type: plain
      asName: KAFKA_ADVERTISED_LISTENERS
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
      type: plain
      asName: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
    KAFKA_CONTROLLER_LISTENER_NAMES:
      type: plain
      asName: KAFKA_CONTROLLER_LISTENER_NAMES
    KAFKA_INTER_BROKER_LISTENER_NAME:
      type: plain
      asName: KAFKA_INTER_BROKER_LISTENER_NAME
    KAFKA_CONTROLLER_QUORUM_VOTERS:
      type: plain
      asName: KAFKA_CONTROLLER_QUORUM_VOTERS
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:
      type: plain
      asName: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:
      type: plain
      asName: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR:
      type: plain
      asName: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS:
      type: plain
      asName: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
    KAFKA_NUM_PARTITIONS:
      type: plain
      asName: KAFKA_NUM_PARTITIONS
    KAFKA_AUTO_CREATE_TOPICS_ENABLE:
      type: plain
      asName: KAFKA_AUTO_CREATE_TOPICS_ENABLE
    KAFKA_LOG_RETENTION_HOURS:
      type: plain
      asName: KAFKA_LOG_RETENTION_HOURS
    KAFKA_LOG_DIRS:
      type: plain
      asName: KAFKA_LOG_DIRS
    KAFKA_HEAP_OPTS:
      type: plain
      asName: KAFKA_HEAP_OPTS
    CLUSTER_ID:
      type: plain
      asName: CLUSTER_ID
