apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- account-runtime.yaml
- match-runtime.yaml
- gateway-runtime.yaml
- edge-authz-runtime.yaml
- integration-ui-runtime.yaml
- proxy-runtime.yaml
- db-ca.yaml
- kafka-runtime.yaml
- account-db-identity.yaml
- match-db-identity.yaml
- db-provision-runtime.yaml
- db-provision-tls.yaml
- gaegaeting-dev-role.yaml
- gaegaeting-dev-binding.yaml
- gaegaeting-dev-kafka-role.yaml
- gaegaeting-dev-kafka-binding.yaml
- databases-role.yaml
- databases-binding.yaml
- cloudflare.yaml
- istio-system-role.yaml
- istio-system-binding.yaml
