apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: gaegaeting-dev-match-runtime
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: gaegaeting
  config: stg
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-gaegaeting-stg
    namespace: doppler-operator-system
  managedSecret:
    name: gaegaeting-match-runtime
    namespace: gaegaeting-dev
    type: Opaque
  secrets:
  - NODE_ENV
  - INTERNAL_AUTH_ASSERTION_SECRET
  - DATABASE_HOST
  - DATABASE_PORT
  - DATABASE_SSL_MODE
  - DATABASE_SYNCHRONIZE
  - MATCH_SERVICE_API_PORT
  - ACCOUNT_SERVICE_HOST
  - KAFKA_BROKERS
  - MATCH_DATABASE_NAME
  - MATCH_DATABASE_USERNAME
  - MATCH_DATABASE_PASSWORD
  - KAFKA_TOPIC_PREFIX
  processors:
    NODE_ENV:
      type: plain
      asName: NODE_ENV
    INTERNAL_AUTH_ASSERTION_SECRET:
      type: plain
      asName: INTERNAL_AUTH_ASSERTION_SECRET
    DATABASE_HOST:
      type: plain
      asName: DATABASE_HOST
    DATABASE_PORT:
      type: plain
      asName: DATABASE_PORT
    DATABASE_SSL_MODE:
      type: plain
      asName: DATABASE_SSL_MODE
    DATABASE_SYNCHRONIZE:
      type: plain
      asName: DATABASE_SYNCHRONIZE
    MATCH_SERVICE_API_PORT:
      type: plain
      asName: MATCH_SERVICE_API_PORT
    ACCOUNT_SERVICE_HOST:
      type: plain
      asName: ACCOUNT_SERVICE_HOST
    KAFKA_BROKERS:
      type: plain
      asName: KAFKA_BROKERS
    MATCH_DATABASE_NAME:
      type: plain
      asName: DATABASE_NAME
    MATCH_DATABASE_USERNAME:
      type: plain
      asName: DATABASE_USERNAME
    MATCH_DATABASE_PASSWORD:
      type: plain
      asName: DATABASE_PASSWORD
    KAFKA_TOPIC_PREFIX:
      type: plain
      asName: KAFKA_TOPIC_PREFIX
