apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: gaegaeting-dev-payment-db-provision-runtime
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: gaegaeting
  config: stg
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-gaegaeting-stg
    namespace: doppler-operator-system
  managedSecret:
    name: gaegaeting-payment-db-provision-runtime
    namespace: databases
    type: Opaque
  secrets:
  - DATABASE_HOST
  - DATABASE_PORT
  - PAYMENT_DATABASE_NAME
  - PAYMENT_DATABASE_USERNAME
  - PAYMENT_DATABASE_PASSWORD
  processors:
    DATABASE_HOST:
      type: plain
      asName: DATABASE_HOST
    DATABASE_PORT:
      type: plain
      asName: DATABASE_PORT
    PAYMENT_DATABASE_NAME:
      type: plain
      asName: PAYMENT_DATABASE_NAME
    PAYMENT_DATABASE_USERNAME:
      type: plain
      asName: PAYMENT_DATABASE_USERNAME
    PAYMENT_DATABASE_PASSWORD:
      type: plain
      asName: PAYMENT_DATABASE_PASSWORD
