apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: gaegaeting-dev-payment-runtime
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: gaegaeting
  config: stg
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-gaegaeting-stg
    namespace: doppler-operator-system
  managedSecret:
    name: gaegaeting-payment-runtime
    namespace: gaegaeting-dev
    type: Opaque
  secrets:
  - NODE_ENV
  - INTERNAL_AUTH_ASSERTION_SECRET
  - DATABASE_HOST
  - DATABASE_PORT
  - DATABASE_SSL_MODE
  - PAYMENT_SERVICE_API_PORT
  - PAYMENT_STORE_ENVIRONMENT
  - PAYMENT_WORKER_ENABLED
  - PAYMENT_PROOF_ENCRYPTION_KEY
  - PAYMENT_APPLE_ENABLED
  - PAYMENT_GOOGLE_ENABLED
  - PAYMENT_DATABASE_NAME
  - PAYMENT_DATABASE_USERNAME
  - PAYMENT_DATABASE_PASSWORD
  - PAYMENT_APPLE_PRODUCT_IDS
  - PAYMENT_GOOGLE_PRODUCT_IDS
  processors:
    NODE_ENV:
      type: plain
      asName: NODE_ENV
    INTERNAL_AUTH_ASSERTION_SECRET:
      type: plain
      asName: INTERNAL_AUTH_ASSERTION_SECRET
    DATABASE_HOST:
      type: plain
      asName: DATABASE_HOST
    DATABASE_PORT:
      type: plain
      asName: DATABASE_PORT
    DATABASE_SSL_MODE:
      type: plain
      asName: DATABASE_SSL_MODE
    PAYMENT_SERVICE_API_PORT:
      type: plain
      asName: PAYMENT_SERVICE_API_PORT
    PAYMENT_STORE_ENVIRONMENT:
      type: plain
      asName: PAYMENT_STORE_ENVIRONMENT
    PAYMENT_WORKER_ENABLED:
      type: plain
      asName: PAYMENT_WORKER_ENABLED
    PAYMENT_PROOF_ENCRYPTION_KEY:
      type: plain
      asName: PAYMENT_PROOF_ENCRYPTION_KEY
    PAYMENT_APPLE_ENABLED:
      type: plain
      asName: PAYMENT_APPLE_ENABLED
    PAYMENT_GOOGLE_ENABLED:
      type: plain
      asName: PAYMENT_GOOGLE_ENABLED
    PAYMENT_DATABASE_NAME:
      type: plain
      asName: DATABASE_NAME
    PAYMENT_DATABASE_USERNAME:
      type: plain
      asName: DATABASE_USERNAME
    PAYMENT_DATABASE_PASSWORD:
      type: plain
      asName: DATABASE_PASSWORD
    PAYMENT_APPLE_PRODUCT_IDS:
      type: plain
      asName: PAYMENT_APPLE_PRODUCT_IDS
    PAYMENT_GOOGLE_PRODUCT_IDS:
      type: plain
      asName: PAYMENT_GOOGLE_PRODUCT_IDS
