apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: gaegaeting-dev-proxy-runtime
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: gaegaeting
  config: stg
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-gaegaeting-stg
    namespace: doppler-operator-system
  managedSecret:
    name: gaegaeting-proxy-runtime
    namespace: gaegaeting-dev
    type: Opaque
  secrets:
  - PROXY_ACCOUNT_HOST
  - PROXY_GATEWAY_HOST
  - PROXY_EDGE_AUTHZ_HOST
  processors:
    PROXY_ACCOUNT_HOST:
      type: plain
      asName: ACCOUNT_HOST
    PROXY_GATEWAY_HOST:
      type: plain
      asName: GATEWAY_HOST
    PROXY_EDGE_AUTHZ_HOST:
      type: plain
      asName: EDGE_AUTHZ_HOST
