apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: platform-argocd
  sources:
  - chart: argo-cd
    helm:
      kubeVersion: 1.36.4
      releaseName: argocd
      valueFiles:
      - $values/gitops/platform/argocd/base.values.yaml
      - $values/gitops/clusters/oci-a1/argocd.values.yaml
      - $values/gitops/platform/argocd/accounts.values.yaml
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 10.8.2
  - ref: values
    repoURL: https://github.com/kangjuhyup/k3s.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      enabled: true
      prune: false
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
