apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: istio
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
    kind: MutatingWebhookConfiguration
  - group: admissionregistration.k8s.io
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
    kind: ValidatingWebhookConfiguration
  project: platform-istio
  sources:
  - chart: base
    helm:
      kubeVersion: 1.36.4
      releaseName: istio-base
      valueFiles:
      - $values/gitops/platform/istio/base.values.yaml
    repoURL: https://blob.istio.io/istio-release/charts
    targetRevision: 1.30.4
  - chart: istiod
    helm:
      kubeVersion: 1.36.4
      releaseName: istiod
      valueFiles:
      - $values/gitops/platform/istio/istiod.values.yaml
    repoURL: https://blob.istio.io/istio-release/charts
    targetRevision: 1.30.4
  - chart: gateway
    helm:
      kubeVersion: 1.36.4
      releaseName: istio-ingress
      valueFiles:
      - $values/gitops/platform/istio/gateway.values.yaml
      - $values/gitops/clusters/oci-a1/ingress.values.yaml
    repoURL: https://blob.istio.io/istio-release/charts
    targetRevision: 1.30.4
  - path: gitops/clusters/oci-a1/istio
    ref: values
    repoURL: https://github.com/kangjuhyup/k3s.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      enabled: true
      prune: false
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
    - RespectIgnoreDifferences=true
