apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd-ingress-project.yaml
- argocd-ingress.yaml
- argocd.yaml
- auth-project.yaml
- auth.yaml
- cert-manager-project.yaml
- cert-manager.yaml
- cnpg-project.yaml
- cnpg.yaml
- doppler-project.yaml
- doppler.yaml
- istio-project.yaml
- istio.yaml
- monitoring-project.yaml
- monitoring.yaml
- platform-project.yaml
- postgresql-project.yaml
- postgresql.yaml
- redis-project.yaml
- redis.yaml
- root-project.yaml
- root.yaml
