apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
  name: platform-postgresql
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  destinations:
  - namespace: databases
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: postgresql.cnpg.io
    kind: Cluster
  sourceRepos:
  - https://github.com/kangjuhyup/k3s.git
