apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '70'
spec:
  project: app-vote
  source:
    repoURL: https://github.com/kangjuhyup/k3s.git
    targetRevision: main
    path: gitops/clusters/oci-a1/vote-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: vote-dev
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
      prune: false
      allowEmpty: false
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
