#!/bin/sh
# Managed by Ansible k3s_user_access: client commands do not read server config.
export K3S_CONFIG_FILE=/dev/null
if [ "$(id -u)" != 0 ]; then
    export KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}"
fi
exec /usr/local/bin/k3s kubectl "$@"
