apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-secret-writer
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: '-30'
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - kafka-runtime
  verbs:
  - update
