apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vote-redis-secret-writer
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: '-30'
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - vote-redis-provision-tls
  verbs:
  - update
