apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gaegaeting-dev-public
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  dnsNames:
  - test-ggt-ui.rvkang.app
  - test-ggt-api.rvkang.app
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: gaegaeting-dev-cloudflare
  secretName: gaegaeting-dev-public-tls
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
