apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: gaegaeting-dev-ui
  namespace: gaegaeting-dev
spec:
  hosts:
  - test-ggt-ui.rvkang.app
  exportTo:
  - istio-system
  gateways:
  - istio-system/gaegaeting-dev-public
  http:
  - name: admin-ui
    match:
    - port: 443
      uri:
        exact: /admin
    - port: 443
      uri:
        prefix: /admin/
    route:
    - destination:
        host: admin-ui
        port:
          number: 8080
  - match:
    - port: 443
    route:
    - destination:
        host: integration-ui
        port:
          number: 8080
