{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "clusterrole-doppler-operator-manager-role.json",
    "clusterrolebinding-doppler-operator-manager-rolebinding.json",
    "configmap-doppler-operator-manager-config.json",
    "customresourcedefinition-dopplersecrets.secrets.doppler.com.json",
    "deployment-doppler-operator-controller-manager.json",
    "namespace-doppler-operator-system.json",
    "role-doppler-operator-leader-election-role.json",
    "rolebinding-doppler-operator-leader-election-rolebinding.json",
    "serviceaccount-doppler-operator-controller-manager.json"
  ]
}
