{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "../../../platform/doppler/install",
    "databases-role.json",
    "databases-binding.json",
    "auth-postgres-sync.json",
    "auth-postgres-identity-sync.json"
  ]
}
