apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../platform/doppler/install
- cert-manager-role.yaml
- cert-manager-binding.yaml
- databases-role.yaml
- databases-binding.yaml
- monitoring-role.yaml
- monitoring-binding.yaml
- auth-postgres-sync.yaml
- auth-postgres-identity-sync.yaml
- auth-redis-sync.yaml
- cloudflare-dns-sync.yaml
- monitoring-grafana-sync.yaml
- monitoring-redis-sync.yaml
- monitoring-slack-sync.yaml
- shared-redis-sync.yaml
- shared-redis-master-tls-sync.yaml
- shared-redis-replica-tls-sync.yaml
