{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "../../../platform/doppler/install",
    "cert-manager-role.json",
    "cert-manager-binding.json",
    "databases-role.json",
    "databases-binding.json",
    "monitoring-role.json",
    "monitoring-binding.json",
    "auth-postgres-sync.json",
    "auth-postgres-identity-sync.json",
    "auth-redis-sync.json",
    "cloudflare-dns-sync.json",
    "monitoring-grafana-sync.json",
    "monitoring-redis-sync.json",
    "monitoring-slack-sync.json",
    "shared-redis-sync.json",
    "shared-redis-master-tls-sync.json",
    "shared-redis-replica-tls-sync.json"
  ]
}
