apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: shared-redis-replica-tls
  namespace: doppler-operator-system
spec:
  config: prd
  host: https://api.doppler.com
  managedSecret:
    name: shared-redis-replica-tls
    namespace: databases
    type: Opaque
  processors:
    REDIS_REPLICA_TLS_CERT:
      asName: tls.crt
      type: plain
    REDIS_REPLICA_TLS_KEY:
      asName: tls.key
      type: plain
    REDIS_TLS_CA_CERT:
      asName: ca.crt
      type: plain
  project: infrastructure
  resyncSeconds: 120
  secrets:
  - REDIS_REPLICA_TLS_CERT
  - REDIS_REPLICA_TLS_KEY
  - REDIS_TLS_CA_CERT
  tokenSecret:
    name: doppler-auth-infrastructure-prd
    namespace: doppler-operator-system
  verifyTLS: true
