apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vote-secret-writer
  namespace: vote-dev
  annotations:
    argocd.argoproj.io/sync-wave: '-30'
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - vote-ui-runtime
  - vote-admin-runtime
  - vote-authz-runtime
  verbs:
  - update
