apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: vote-redis-upstream
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: vote
  config: prd
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-vote-prd
    namespace: doppler-operator-system
  managedSecret:
    name: vote-redis-upstream
    namespace: vote-dev
    type: Opaque
  secrets:
  - REDIS_UPSTREAM_HOST
  - REDIS_UPSTREAM_PORT
  processors:
    REDIS_UPSTREAM_HOST:
      type: plain
      asName: REDIS_UPSTREAM_HOST
    REDIS_UPSTREAM_PORT:
      type: plain
      asName: REDIS_UPSTREAM_PORT
