apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: vote-authz-runtime
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
spec:
  project: vote
  config: prd
  host: https://api.doppler.com
  verifyTLS: true
  resyncSeconds: 120
  tokenSecret:
    name: doppler-auth-vote-prd
    namespace: doppler-operator-system
  managedSecret:
    name: vote-authz-runtime
    namespace: vote-dev
    type: Opaque
  secrets:
  - AUTH_OIDC_ISSUER
  - AUTH_OIDC_TENANT_CODE
  - VOTE_AUTH_TENANT_ID
  - VOTE_AUTH_AUDIENCE
  - VOTE_AUTH_INTROSPECTION_CLIENT_ID
  - VOTE_AUTH_INTROSPECTION_CLIENT_SECRET
  - VOTE_AUTHZ_ASSERTION_KEY
  processors:
    AUTH_OIDC_ISSUER:
      type: plain
      asName: AUTH_OIDC_ISSUER
    AUTH_OIDC_TENANT_CODE:
      type: plain
      asName: AUTH_OIDC_TENANT_CODE
    VOTE_AUTH_TENANT_ID:
      type: plain
      asName: VOTE_AUTH_TENANT_ID
    VOTE_AUTH_AUDIENCE:
      type: plain
      asName: VOTE_AUTH_AUDIENCE
    VOTE_AUTH_INTROSPECTION_CLIENT_ID:
      type: plain
      asName: VOTE_AUTH_INTROSPECTION_CLIENT_ID
    VOTE_AUTH_INTROSPECTION_CLIENT_SECRET:
      type: plain
      asName: VOTE_AUTH_INTROSPECTION_CLIENT_SECRET
    VOTE_AUTHZ_ASSERTION_KEY:
      type: plain
      asName: VOTE_AUTHZ_ASSERTION_KEY
