apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: admin-ui-ingress
  namespace: gaegaeting-dev
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: admin-ui
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
    ports:
    - protocol: TCP
      port: 8080
