apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gaegaeting-dev
  namespace: argocd
spec:
  project: app-gaegaeting-dev
  source:
    repoURL: https://github.com/kangjuhyup/k3s.git
    targetRevision: main
    path: gitops/clusters/oci-a1/gaegaeting-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: gaegaeting-dev
  syncPolicy:
    automated:
      enabled: false
      selfHeal: true
      prune: false
      allowEmpty: false
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gaegaeting-dev-secrets
  namespace: argocd
spec:
  project: app-gaegaeting-dev
  source:
    repoURL: https://github.com/kangjuhyup/k3s.git
    targetRevision: main
    path: gitops/clusters/oci-a1/gaegaeting-dev/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: doppler-operator-system
  syncPolicy:
    automated:
      enabled: false
      selfHeal: true
      prune: false
      allowEmpty: false
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gaegaeting-dev-kafka
  namespace: argocd
spec:
  project: app-gaegaeting-dev
  source:
    repoURL: https://github.com/kangjuhyup/k3s.git
    targetRevision: main
    path: gitops/clusters/oci-a1/gaegaeting-dev/kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: gaegaeting-dev-kafka
  syncPolicy:
    automated:
      enabled: false
      selfHeal: true
      prune: false
      allowEmpty: false
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gaegaeting-dev-database
  namespace: argocd
spec:
  project: app-gaegaeting-dev
  source:
    repoURL: https://github.com/kangjuhyup/k3s.git
    targetRevision: main
    path: gitops/clusters/oci-a1/gaegaeting-dev/database
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    automated:
      enabled: false
      selfHeal: true
      prune: false
      allowEmpty: false
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gaegaeting-dev-ingress
  namespace: argocd
spec:
  project: app-gaegaeting-dev
  source:
    repoURL: https://github.com/kangjuhyup/k3s.git
    targetRevision: main
    path: gitops/clusters/oci-a1/gaegaeting-dev/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      enabled: false
      selfHeal: true
      prune: false
      allowEmpty: false
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
