apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: edge-proxy-ingress
  namespace: gaegaeting-dev
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: edge-proxy
      app.kubernetes.io/part-of: gaegaeting
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
    ports:
    - port: 8080
      protocol: TCP
