apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  replicas: 0
  selector:
    matchLabels: &id001
      app.kubernetes.io/name: gateway
      app.kubernetes.io/part-of: gaegaeting
  template:
    metadata:
      labels: *id001
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: gateway
        image: ghcr.io/kangjuhyup/gaegaeting/gateway:sha-317f550e3fb4fbd773a606c1d58293e3cf7cb32d@sha256:4756b8bac28027b6293ff9b6744c21f7a6161d9483a5a557681f52afcadbb67d
        ports:
        - name: http
          containerPort: 4000
        envFrom:
        - secretRef:
            name: gaegaeting-gateway-runtime
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        startupProbe:
          httpGet:
            path: /gateway/health
            port: http
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /gateway/health
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /gateway/health
            port: http
          periodSeconds: 20
          failureThreshold: 3
