apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- account.yaml
- account-service.yaml
- account-migration.yaml
- match.yaml
- match-service.yaml
- match-migration.yaml
- gateway.yaml
- gateway-service.yaml
- edge-authz.yaml
- edge-authz-service.yaml
- integration-ui.yaml
- integration-ui-service.yaml
- network-policy.yaml
- edge-proxy-config.yaml
- edge-proxy.yaml
- edge-proxy-service.yaml
- edge-proxy-policy.yaml
