apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../apps/gaegaeting
- namespace.yaml
- edge-proxy-config.yaml
- edge-proxy-policy.yaml
- account-ingress-policy.yaml
- match-ingress-policy.yaml
- gateway-ingress-policy.yaml
- edge-authz-ingress-policy.yaml
- integration-ui-ingress-policy.yaml
- secrets
- database
- ingress
- retired-kafka-namespace.yaml
patchesStrategicMerge:
- account-patch.yaml
- match-patch.yaml
- gateway-patch.yaml
- edge-authz-patch.yaml
- integration-ui-patch.yaml
- edge-proxy-patch.yaml
