apiVersion: apps/v1
kind: Deployment
metadata:
  name: match
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  replicas: 0
  selector:
    matchLabels: &id001
      app.kubernetes.io/name: match
      app.kubernetes.io/part-of: gaegaeting
  template:
    metadata:
      labels: *id001
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: match
        image: ghcr.io/kangjuhyup/gaegaeting/match:sha-317f550e3fb4fbd773a606c1d58293e3cf7cb32d@sha256:3d2c5f34e107ba1dea569f49c8e58900d156fb09864114e75f030e2a93ad9df3
        ports:
        - name: http
          containerPort: 2801
        envFrom:
        - secretRef:
            name: gaegaeting-match-runtime
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        startupProbe:
          httpGet:
            path: /match/health
            port: http
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /match/health
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /match/health
            port: http
          periodSeconds: 20
          failureThreshold: 3
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/database/ca.crt
        volumeMounts:
        - name: db-ca
          mountPath: /etc/database
          readOnly: true
      volumes:
      - name: db-ca
        secret:
          secretName: gaegaeting-db-ca
