apiVersion: batch/v1
kind: Job
metadata:
  name: match-migration-317f550e3fb4
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  suspend: true
  backoffLimit: 0
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: match
        app.kubernetes.io/part-of: gaegaeting
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: match
        image: ghcr.io/kangjuhyup/gaegaeting/match:sha-317f550e3fb4fbd773a606c1d58293e3cf7cb32d@sha256:3d2c5f34e107ba1dea569f49c8e58900d156fb09864114e75f030e2a93ad9df3
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/database/ca.crt
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: gaegaeting-match-runtime
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: gaegaeting-match-runtime
              key: DATABASE_PORT
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: gaegaeting-match-runtime
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gaegaeting-match-runtime
              key: DATABASE_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: gaegaeting-match-runtime
              key: DATABASE_NAME
        - name: DATABASE_SSL_MODE
          valueFrom:
            secretKeyRef:
              name: gaegaeting-match-runtime
              key: DATABASE_SSL_MODE
        volumeMounts:
        - name: db-ca
          mountPath: /etc/database
          readOnly: true
        workingDir: /app
        command:
        - node
        - dist/src/migrations/migrate.js
      volumes:
      - name: db-ca
        secret:
          secretName: gaegaeting-db-ca
      restartPolicy: Never
