apiVersion: v1
kind: Service
metadata:
  name: account
  namespace: gaegaeting-dev
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  selector:
    app.kubernetes.io/name: account
    app.kubernetes.io/part-of: gaegaeting
  ports:
  - name: http
    port: 2800
    targetPort: http
