apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../apps/auth
- auth-bootstrap-sync.yaml
- auth-runtime-sync.yaml
- auth-service-destination.yaml
- auth-ui-destination.yaml
- certificate.yaml
- gateway.yaml
- hpa.yaml
- namespace.yaml
- route.yaml
- secret-writer-binding.yaml
- secret-writer-role.yaml
patchesStrategicMerge:
- auth-service-patch.yaml
- auth-ui-patch.yaml
- auth-worker-patch.yaml
- migration-patch.yaml
